### ISSUE TITLE
Theme appears broken in kanboard v1.2.30 (latest release)

### ISSUE THREAD

**Issue by dangerstudios** [greyaz/ThemeRevision#23]
This theme breaks the UI in the latest kanboard release:
https://github.com/kanboard/kanboard/releases/tag/v1.2.30

![image](https://github.com/greyaz/ThemeRevision/assets/63320852/a0e7fb87-8388-440a-8458-7d13e4bccd3a)
![image](https://github.com/greyaz/ThemeRevision/assets/63320852/1f5e8c43-4a0c-4868-b1c8-7ec86c29ce83)

**Comment by trebor2109** [comment]
The problem exists since Kanboard V1.2.29 when the new theme support (dark, light, automatic) was added. So the last working version of Kanboard for this theme here is version 1.2.28. It would be very cool if the theme here is adapted accordingly, that it also works under the current version (1.2.30). Thanks for the work on this theme.

**Comment by xyttyxy** [comment]
In 1.2.28 the visuals work but I cannot create new columns, swimlanes or rename existing ones. Clicking the save button has no effect. 

Edit: just checked on KB 1.2.27 the above 2 points are working

**Comment by pittss** [comment]
Quick fix:

In file: <work_dir>/plugins/ThemeRevision/Template/layout.php
Replace line 17
```
<?= $this->asset->css('assets/css/app.min.css') ?>
```
To
```
<?php if (! isset($not_editable)): ?>
	<?= $this->asset->css('assets/css/'.$this->user->getTheme().'.min.css') ?>
<?php else: ?>
	<?= $this->asset->css('assets/css/light.min.css') ?>
<?php endif ?>
```

**Comment by mikhailnov** [comment]
+1 for this

**Comment by DangerDrome** [comment]
@greyaz was this updated in the code reop or do we have to apply the quickfix mentione above?
